Replace custom cloneSchema with mongoose's schema.clone() utility
Trouva/mongoose-version pull request #5
Opened 2021-08-18 09:06 UTC by AndreJoaquim

2021-08-18 14:07 UTC, rmdp-trouva approved these changes

2021-08-18 14:23 UTC, cryptotavares commented on lib/save-collection.js
> -    cloneSchema = require('./clone-schema'),
Can't we remove the `./clone-schema` lib as well? 😅

2021-08-18 15:19 UTC, codelamp commented on lib/save-collection.js
> -    cloneSchema = require('./clone-schema'),
Do we know the differences between the behaviours? As the original clone code had specific index removals and other options. Uncertain as to if these would have/bring issues.

2021-08-18 17:26 UTC, AndreJoaquim commented on lib/save-collection.js
> -    cloneSchema = require('./clone-schema'),
Now that we have a test suite, I'm now going to run the tests to see. I don't know exactly the difference between the behaviours, only that `schema.clone()` was not available in mongoose 3.x

2021-08-18 18:13 UTC, AndreJoaquim commented on lib/save-collection.js
> -    cloneSchema = require('./clone-schema'),
@codelamp You're right, the `schema.clone()` doesn't remove index, sparse, nor unique options. I've added the code to reflect that and I've added tests for that scenario

2021-08-19 11:34 UTC, AndreJoaquim commented on README.md
> -| mongoose | `require("mongoose")` | Pass a mongoose instance to work with |
As I've added `mongoose` as a peerDependency, this is not required anymore. We assume the consuming application has mongoose installed 👍🏻

2021-08-19 11:35 UTC, AndreJoaquim commented on package.json
>    },
We need to keep the devDependency due to tests

2021-08-20 12:12 UTC, cryptotavares approved these changes

2021-08-20 15:26 UTC, codelamp requested changes
Everything looks great 👌  apart from the unique indexes issue.

2021-08-20 15:26 UTC, codelamp commented on lib/clone-schema.js
> +        delete schematype.options.unique;
I believe unique indexes might cause an issue, because of the way versions work. So we might have to remove `unique` from the index anyway. I have no idea about sparse 😅

2021-08-20 15:27 UTC, AndreJoaquim commented on lib/clone-schema.js
> +        delete schematype.options.unique;
Agreed!

2021-08-20 15:53 UTC, codelamp approved these changes
Looks good 👌 Nice!

2021-08-20 16:08 UTC, merged